### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by spotrop** [tsy7/ENCRYpt#1]
So.... This program doesn't work if you don't have internet????

And why use an API?
MD5 is easy to calculate locally without an API and doesn't take much resource power...
Not to mention that it would be 1000 times slower using an API?

Cool script but what's the point in using a web API over local calculation?

Also, just as a heads up, you can use a Gemfile instead of a bash script to make it cross platform. Otherwise it's just Linux that can run the installer.

And not to nick-pick, but

```rb
loop do
```

Is not a for loop. It's shorthand for a while true loop.

Obviously, you are someone who has just started to learn coding which is great and good luck with it, but there are a lot more better ways to do this :)

```rb
require 'digest'

md5 = Digest::MD5.new()
md5.update "hello"
puts md5.hexdigest
```

**Comment by tsy7** [comment]
I respect your opinion very much thanks for the constructive criticism but
I'm a very newbie in ruby and I studied this digest/md5 library and we will
continue to learn

**Comment by spotrop** [comment]
No problem at all :) I hope you get far with your learning and would love to see some more projects from you.
